# Generated by Django 6.0.3 on 2026-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(choices=[('software', 'Software Development'), ('marketing', 'Digital Marketing'), ('business', 'Business Development'), ('internship', 'Internship'), ('consultation', 'Consultation'), ('other', 'Other')], max_length=50)),
                ('project_budget', models.CharField(blank=True, choices=[('under-50k', 'Under 50K'), ('50k-1l', '50K-1L'), ('1l-5l', '1L-5L'), ('5l-10l', '5L-10L'), ('above-10l', 'Above 10L')], max_length=50)),
                ('urgency', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('1-month', '1 Month'), ('3-months', '3 Months'), ('6-months', '6 Months'), ('flexible', 'Flexible')], max_length=50)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
