# Generated by Django 6.0.3 on 2026-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
