# Generated by Django 6.0.3 on 2026-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_type', models.CharField(choices=[('python_ds', 'Python Data Science'), ('web_dev', 'Web Development'), ('ai_ml', 'AI/ML')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('cgpa', models.CharField(blank=True, max_length=20)),
                ('skills', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('motivation', models.TextField()),
                ('availability', models.CharField(max_length=50)),
                ('resume', models.URLField(blank=True)),
                ('terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
