# Generated by Django 6.0.3 on 2026-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internshipapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='internship_type',
            field=models.CharField(max_length=100),
        ),
    ]
