# Generated by Django 6.0.3 on 2026-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_webinarregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarregistration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
